name: Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Install Angular
      run: npm install -g @angular/cli

    - name: Build Angular project
      run: ng build --configuration production

    - name: FTP Deploy
      uses: modern-dev/ftp-mirror@v2
      with:
        server: ${{ secrets.FTP_SERVER_NAME }}
        user: ${{ secrets.FTP_SERVER_USER }}
        password: ${{ secrets.FTP_SERVER_PASSWORD }}
        remote_dir: /htdocs
        delete: true
        
